steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-run-service', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-run-service']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'cloud-run-service', '--image', 'gcr.io/$PROJECT_ID/cloud-run-service', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']